# Change these first
owner: uandreew # Your GitHub organization or username, where this repository lives
repo: status.noleron.com # The name of this repository

sites:
  - name: OPSP
    url: https://opulus.space
  - name: NL WEB
    url: https://noleron.com
  - name: NL Social
    url: https://social.noleron.com
  - name: NL Matrix (Server)
    url: https://noleron.com
  - name: NL Matrix (Client Element)
    url: https://mx.noleron.com
  - name: NL Matrix (Client Cinny)
    url: https://cinny.noleron.com
  - name: NL Pass
    url: https://pass.noleron.com
  - name: NL Blog
    url: https://blog.noleron.com
  - name: NL Mail
    url: https://mail.noleron.com
  - name: NL Git
    url: https://git.noleron.com
  - name: NL Lunarium
    url: https://lunarium.noleron.com
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.noleron.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.noleron.com
  introTitle: "**status.noleron.com** сторінка статусу сервісів noleron.com та opulus.space."
  introMessage: Тут показується які сервіси зараз в онлайні, а які не працюють.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
